# PostgreSQL. Versions 8.2 and up are supported.
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: hyper_development
  pool:     5
  username: hyper
  password: nohaymonedas
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: hyper_test
  pool:     5
  username: hyper
  password: nohaymonedas
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: hyper_production
  pool:     5
  username: hyper
  password: nohaymonedas
  template: template0
