# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV.fetch("SENDGRID_USERNAME") %>
  email_provider_password: <%= ENV.fetch("SENDGRID_PASSWORD") %>
  domain_name: <%= ENV.fetch("DOMAIN_NAME") %>
  secret_key_base: 809b7de3e6961715c4ba252e398cc411abd9186d79d0047e22475ebace0fd64dbd34adb6511e5fd6129bf174cd91e6b9f84694e8ea2c33dcb187b5df0fde3aa8
  facebook_app_id: <%= ENV.fetch("FACEBOOK_APP_ID") %>
  facebook_app_secret: <%= ENV.fetch("FACEBOOK_APP_SECRET") %>
  bing_account_key: <%= ENV.fetch("BING_ACCOUNT_KEY") %>
  twitter_api_key: <%= ENV.fetch("TWITTER_API_KEY") %>
  twitter_api_secret: <%= ENV.fetch("TWITTER_API_SECRET") %>
  tumblr_api_key: <%= ENV.fetch("TUMBLR_API_KEY") %>
  tumblr_api_secret: <%= ENV.fetch("TUMBLR_API_SECRET") %>
  aws_s3_bucket: <%= ENV.fetch("AWS_S3_BUCKET") %>
  aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  aws_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  aws_arn: <%= ENV.fetch("AWS_ARN") %>
test:
  domain_name: hyper.test 
  secret_key_base: 069664adf011b483094c69a8755e7497962584af6dba6162108ccb32be0c59853d985fceeb9159d3d0f76a6540c62aed65f65d75fa2fbadca245d67be027b7d5
  facebook_app_id: '775337459177377'
  facebook_app_secret: d5eb4d69011e72718f065415cf84a453
  aws_s3_bucket: <%= ENV.fetch("AWS_S3_BUCKET") %>
  aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  aws_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  aws_arn: arn:aws:sns:us-east-1:000086100001:app/APNS_SANDBOX/hyper-test
  bing_account_key: 3aE/8Du531krOVcT/+R/kQZtTnq1WXZ3OUkzSRE1qMc
  fb_valid_user_id: "10204401232955921"
  fb_valid_token: CAALBKlHV16EBAIX2Hr0T0CohHxdGLG7A56ewdWCN1ZCxE9b1wsZBn0doTqKmbEoR4O5FrJYI9xCLgwoCkciZB57fKZCRZAXaWjtBuXtZCtXAZCNaKbqGGLerrwxmdqN43mQZCWGeZBEr4cgkpfIaWgCAdFXxD41UDmvqcFH7fvB8fDEVdVsaOePGveaOkrQlxfK8ZD

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  email_provider_username: <%= ENV.fetch("SENDGRID_USERNAME") %>
  email_provider_password: <%= ENV.fetch("SENDGRID_PASSWORD") %> 
  domain_name: <%= ENV.fetch("DOMAIN_NAME") %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  aws_s3_bucket: <%= ENV.fetch("AWS_S3_BUCKET") %>
  aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  aws_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  aws_arn: <%= ENV.fetch("AWS_ARN") %>
  facebook_app_id: <%= ENV.fetch("FACEBOOK_APP_ID") %>
  facebook_app_secret: <%= ENV.fetch("FACEBOOK_APP_SECRET") %>
  dsn: https://202714598a5b4c70b65b375b71dd3fa9:3a47f2c1969142cd87f1c86effbec441@app.getsentry.com/26533
  bing_account_key: <%= ENV.fetch("BING_ACCOUNT_KEY") %>
  twitter_api_key: <%= ENV.fetch("TWITTER_API_KEY") %>
  twitter_api_secret: <%= ENV.fetch("TWITTER_API_SECRET") %>
  tumblr_api_key: <%= ENV.fetch("TUMBLR_API_KEY") %>
  tumblr_api_secret: <%= ENV.fetch("TUMBLR_API_SECRET") %>

production:
  email_provider_username: <%= ENV.fetch("SENDGRID_USERNAME") %>
  email_provider_password: <%= ENV.fetch("SENDGRID_PASSWORD") %> 
  domain_name: <%= ENV.fetch("DOMAIN_NAME") %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  aws_s3_bucket: <%= ENV.fetch("AWS_S3_BUCKET") %>
  aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
  aws_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
  aws_arn: <%= ENV.fetch("AWS_ARN") %>
  facebook_app_id: <%= ENV.fetch("FACEBOOK_APP_ID") %>
  facebook_app_secret: <%= ENV.fetch("FACEBOOK_APP_SECRET") %>
  bing_account_key: <%= ENV.fetch("BING_ACCOUNT_KEY") %>
  twitter_api_key: <%= ENV.fetch("TWITTER_API_KEY") %>
  twitter_api_secret: <%= ENV.fetch("TWITTER_API_SECRET") %>
  tumblr_api_key: <%= ENV.fetch("TUMBLR_API_KEY") %>
  tumblr_api_secret: <%= ENV.fetch("TUMBLR_API_SECRET") %>